In [9]:
#cam be casted as a numpy array
#by Prabesh Paudel
import numpy as np

In [2]:
my_list = [1,2,3]
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
#this can cast a 2D array into matrix form
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#just like range function in regular python, there "arange" in numpy to get a range of values
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#to get an array of zeros, we can go numpy.zeros(x) where x is the number of elements we want
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5)) #or we can pass in a tuple to get a matrix of 5x5 rows x columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#ones too
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#to get an array of doubles which are evenly spaced
np.linspace(1,5,10) #10 evenly spaced items ranging from 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
np.eye(4)  #get a identity matrix (4x4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5) #you get a single dimensional array of 5 random numbers between 0 and 1

array([0.17589576, 0.6745621 , 0.17253997, 0.4328654 , 0.56412833])

In [18]:
np.random.rand(5,5) #you get a 5x5 matrix of random numbers

array([[0.29167148, 0.04718941, 0.12265228, 0.96092831, 0.42145972],
       [0.40086722, 0.23712899, 0.75298304, 0.45229833, 0.94920142],
       [0.85432286, 0.04425392, 0.42751982, 0.32115706, 0.09202491],
       [0.49060874, 0.06386948, 0.10923722, 0.80910013, 0.24202417],
       [0.53201838, 0.12913551, 0.64572518, 0.36013588, 0.98525329]])

In [22]:
np.random.randn(2) #we get two random values from the normal distribution

array([ 0.32241414, -0.86388384])

In [23]:
np.random.randn(4,4) #4x4 matrix of values from normal distribution

array([[-0.23278642,  0.67387657, -0.80869453,  0.10398492],
       [-0.03327894, -0.48834642,  1.04096232, -1.4970172 ],
       [-0.88532255,  0.16021602,  0.00890579, -0.04832626],
       [ 1.56665597,  1.64019478,  0.23583595,  0.0397623 ]])

In [26]:
np.random.randint(1,101) #random number

34

In [27]:
np.random.randint(1,101,10) #get 10 random integers from 1-100 

array([22, 67, 84,  9, 50, 88, 98, 60, 62, 80])

In [30]:
arr = np.arange(25) #you already know

In [32]:
arr.reshape(5,5) #can reshape a single dimensional array to a matrix but has to have exactly enough elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
randarray = np.random.randint(0,101, 20)

In [36]:
randarray

array([ 6, 50, 62, 18, 66, 57, 19, 25, 84,  6, 81, 46, 89, 39, 35, 62,  2,
       30, 66, 98])

In [40]:
randarray.min() #min

2

In [39]:
randarray.max() #max

98

In [41]:
randarray.argmax() #return index of max value

19

In [42]:
randarray.argmin()

16

In [43]:
newarr = np.random.randint(1,101,25)

In [46]:
newarr.shape #get simension of newarr

(25,)

In [47]:
newarr = newarr.reshape(5,5)

In [48]:
newarr.shape

(5, 5)

In [50]:
newarr.dtype #get data type

dtype('int64')

In [53]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8] #general indexing

8

In [55]:
arr[1:5] #just like regular python

array([1, 2, 3, 4])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5] = 100 #the array is brodcasted so we can chage the values in it.
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr = np.arange(0,11) #reset
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr_slice = arr[:5]
arr_slice[:] = 99 #this changes value in arr as well because arr_slice is just a reference to the values in arr

In [62]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [63]:
#to avoid this, we can use arr.copy()
arr_copy = arr.copy()
arr_copy[:] = 23

In [64]:
arr_copy

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [65]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [68]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]]) #creating a 2d array

In [69]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr_2d[2][1] #third row and second column || multi-dimensional indexing

8

In [74]:
arr_2d[1,1] #same thing but using commas

5

In [76]:
arr_2d[:2, 1:] #grab everything upto the second row index and everything including and after column index 1

array([[2, 3],
       [5, 6]])

In [77]:
#conditional selection
new_array = np.arange(1,11)

In [80]:
bool_array = new_array >5

In [81]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [82]:
new_array[bool_array]

array([ 6,  7,  8,  9, 10])

In [83]:
#you generally go this in a single line
new_array[new_array<5]

array([1, 2, 3, 4])

In [84]:
myarr = np.arange(0,11)

In [85]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
myarr+myarr #adding two arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
myarr + 32 #array is brodcasted so adding a scalar to all the values

array([32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [93]:
myarr * 3 #multiplying by a scalar

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [96]:
myarr * myarr #multiplying by an array by array basis || works for everything

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [97]:
myarr / myarr

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [98]:
#you dont really get an error but it executes but gives you a warning and replace the value by NaN

In [100]:
1/myarr #here you get inf

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [102]:
np.sqrt(myarr) #you get square root of all the values

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [104]:
np.sin(myarr) #you get sine value of every element

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [105]:
np.log(myarr)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

All the numpy operations can be found here: https://docs.scipy.org/doc/numpy/reference/ufuncs.html